application:
  version: @project.version@
  name: cloud-knowledgebase-service
  instance-id: ${random.uuid}

spring:
  datasource:
    hikari:
      data-source-properties:
        ssl: false
  jpa:
    show-sql: true
    data:
      web:
        pageable:
          default-page-size: 20
          page-parameter: page
          size-parameter: pageSize
          sort-parameter: orderBy

server:
  port: 8081