application:
  version: @project.version@
  name: cloud-knowledgebase-service
  instance-id: ${random.uuid}

spring:
  datasource:
    hikari:
      data-source-properties:
        ssl: false # TODO remove it before PR
  jpa:
    show-sql: true
    data:
      web:
        pageable:
          default-page-size: 20
          max-page-size: 60
          one-indexed-parameters: false
          page-parameter: page
          size-parameter: size
          sort-parameter: sort

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

server:
  port: 8081