replicaCount: 2

image:
  tag: 0.5.2

docker:
  logs:
    cluster: de-1
    logstashHosts: sh1aelks.coresuite.com,sh2belks.coresuite.com

ingress:
  hosts:
    - gw.de-1.coreinfra.io
    - ingress.de-1.coreinfra.io
    - de.coresystems.net

service:
  hostname: de-1.coreinfra.io

config:
  example: "Example value from config map. de-1 values"
  logging:
    level:
      org.zalando.logbook.Logbook: DEBUG
