replicaCount: 2

image:
  tag: 0.5.2

docker:
  logs:
    cluster: ie-1
    logstashHosts: sh1aelks.coresuite.com,sh2belks.coresuite.com

ingress:
  hosts:
    - gw.ie-1.coreinfra.io
    - ingress.ie-1.coreinfra.io
    - ie.coresystems.net

service:
  hostname: ie-1.coreinfra.io

config:
  example: "Example value from config map. ie-1 values"
  logging:
    level:
      org.zalando.logbook.Logbook: DEBUG
