{{- if .Values.ingress.enabled -}}
{{- $name := include "chart.name" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{- include "default_metadata" . | indent 2 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        {{- range $ingressPath }}
          - path: {{ . }}
            backend:
              serviceName: {{ $name }}
              servicePort: http
        {{- end }}
  {{- end }}
{{- end }}
